select * from customer limit 20

--Qn1 what is the total revenue generated by male and female?
select gender,sum(purchase_amount) as revenue from customer group by gender

--Qn2 which customers used a discount but still spent more than the average purchase amount?
select customer_id ,purchase_amount from customer where discount_applied ='Yes' and 
purchase_amount>=(select avg(purchase_amount) from customer)

--Qn 3 which are the top five products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer group by item_purchased order by avg(review_rating) desc limit 5;

--Qn 4 Compare the average purchase amount between standard and express shipping?
select shipping_type, round(avg(purchase_amount),2) as "Purchase Amounts" from customer
where shipping_type in ('Standard','Express') group by shipping_type;

--Qn 5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2)
as avg_spend,round(sum(purchase_amount),2) as total_revenue from customer 
group by subscription_status order by total_revenue,avg_spend desc;

--Qn 6 which 5 products have the highest percentage of purchases with discounts applies?
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer group by item_purchased order by discount_rate desc limit 5;

--Qn 7 segments customers into new,returning, and loyal based on their total number of previous purchases and show the count of each segment?
with customer_type as(
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New'
when previous_purchases between 1 and 10 then 'Returning'
else 'loyal' end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of Customers" from customer_type group by customer_segment

--Qn 8 what are the top three products purchased from each category?
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

--Qn 9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Qn 10 what is the revenue contribution of each group?
select age_group,sum(purchase_amount) as total_revenue from customer
group by age_group order by total_revenue desc;



